# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='last_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Last fetched market price (delayed, for display only).',
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='symbol',
            name='last_price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
