# Generated by Django 6.0.2 on 2026-02-16 06:08

from django.db import migrations

def seed_symbols(apps, schema_editor):
    Symbol = apps.get_model("exchange", "Symbol")

    symbols = [
        "AAPL", "TSLA", "MSFT", "NVDA", "GOOGL",
        "AMZN", "META", "NFLX", "AMD", "INTC"
    ]

    for name in symbols:
        Symbol.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_symbol_last_price'),
    ]

    operations = [
        migrations.RunPython(seed_symbols),
    ]
