# Generated by Django 6.0.2 on 2026-02-16 06:28

from django.db import migrations
from decimal import Decimal

def seed_market_maker(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Portfolio = apps.get_model("exchange", "Portfolio")
    Holding = apps.get_model("exchange", "Holding")
    Symbol = apps.get_model("exchange", "Symbol")

    user, created = User.objects.get_or_create(username="market_maker")

    if created:
        user.set_password("market1234")
        user.save()

        Portfolio.objects.create(
            user=user,
            available_balance=Decimal("10000000"),
            reserved_balance=Decimal("0"),
        )

    symbols = Symbol.objects.all()
    for symbol in symbols:
        Holding.objects.get_or_create(
            user=user,
            symbol=symbol,
            defaults={
                "available_quantity": 5000,
                "reserved_quantity": 0
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_seed_symbols'),
    ]

    operations = [
        migrations.RunPython(seed_market_maker),
    ]
