# Generated by Django 6.0.2 on 2026-02-16 06:28

from django.db import migrations
from django.contrib.auth.hashers import make_password
from decimal import Decimal

def seed_market_maker(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Portfolio = apps.get_model("exchange", "Portfolio")
    Holding = apps.get_model("exchange", "Holding")
    Symbol = apps.get_model("exchange", "Symbol")

    user, created = User.objects.get_or_create(
        username="market_maker",
        defaults={"password": make_password("market1234")}
    )

    if created:
        Portfolio.objects.create(
            user=user,
            available_balance=Decimal("10000000"),
            reserved_balance=Decimal("0"),
        )
    else:
        if not user.password:
            user.password = make_password("market1234")
            user.save()

    symbols = Symbol.objects.all()
    for symbol in symbols:
        Holding.objects.get_or_create(
            user=user,
            symbol=symbol,
            defaults={
                "available_quantity": 5000,
                "reserved_quantity": 0
            }
        )


def reverse_seed_market_maker(apps, schema_editor):
    """Reverse: delete market_maker user and related data (optional)."""
    User = apps.get_model("auth", "User")
    try:
        user = User.objects.get(username="market_maker")
        user.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_seed_symbols'),
    ]

    operations = [
        migrations.RunPython(seed_market_maker, reverse_seed_market_maker),
    ]
